2024-12-21 04:13:52,041 - Unhandled exception in listener callback
Traceback (most recent call last):
  File "C:\ZDevelopment\pyEmployee\myenv\Lib\site-packages\pynput\_util\win32.py", line 386, in _handler
    converted = self._convert(code, msg, lpdata)
  File "C:\ZDevelopment\pyEmployee\myenv\Lib\site-packages\pynput\_util\win32.py", line 401, in _convert
    raise NotImplementedError()
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ZDevelopment\pyEmployee\myenv\Lib\site-packages\pynput\_util\__init__.py", line 229, in inner
    return f(self, *args, **kwargs)
  File "C:\ZDevelopment\pyEmployee\myenv\Lib\site-packages\pynput\_util\win32.py", line 390, in _handler
    self._handle(code, msg, lpdata)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
TypeError: '_thread._ThreadHandle' object is not callable
